DECISIVE_LEVEL_POINTS = {
    -3: 0,
    -2: 5,
    -1: 15,
    0: 35,
    1: 60,
    2: 70,
    3: 80,
    4: 90,
    5: 100,
}


SORARE_SCORING_MATRIX = {
    "goals": {
        "sofascore_column": "goals",
        "main_column": "player_goals",
        "sorare_action": "Goal",
        "category": "Decisive",
        "scoring_type": "decisive_positive",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Goal affects Sorare Decisive Score level, not only All-Around points.",
    },
    "goal_assist": {
        "sofascore_column": "goal_assist",
        "main_column": "player_goal_assist",
        "sorare_action": "Assist",
        "category": "Decisive",
        "scoring_type": "decisive_positive",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Assist affects Sorare Decisive Score level.",
    },
    "penalty_won": {
        "sofascore_column": "penalty_won",
        "main_column": "player_penalty_won",
        "sorare_action": "Penalty won",
        "category": "Decisive",
        "scoring_type": "decisive_positive",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Penalty won affects Sorare Decisive Score level.",
    },
    "gk_clean_sheet": {
        "sofascore_column": "clean_sheet_60",
        "main_column": "player_gk_clean_sheet",
        "sorare_action": "Clean sheet",
        "category": "Decisive",
        "scoring_type": "decisive_positive",
        "points": None,
        "applies_to_positions": ["GK"],
        "notes": "Derived stat: goalkeeper played at least 60 minutes and team conceded zero goals. Clean sheet is a Sorare Decisive action only for goalkeepers.",
    },
    "penalty_save": {
        "sofascore_column": "penalty_save",
        "main_column": "player_penalty_save",
        "sorare_action": "Penalty save",
        "category": "Decisive",
        "scoring_type": "decisive_positive",
        "points": None,
        "applies_to_positions": ["GK"],
        "notes": "Penalty save affects Sorare Decisive Score level.",
    },
    "clearance_off_line": {
        "sofascore_column": "clearance_off_line",
        "main_column": "player_clearance_off_line",
        "sorare_action": "Clearance off the line",
        "category": "Decisive",
        "scoring_type": "decisive_positive",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Clearance off the line affects Sorare Decisive Score level.",
    },
    "last_man_tackle": {
        "sofascore_column": "last_man_tackle",
        "main_column": "player_last_man_tackle",
        "sorare_action": "Last-man tackle",
        "category": "Decisive",
        "scoring_type": "decisive_positive",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Last-man tackle affects Sorare Decisive Score level.",
    },
    "own_goals": {
        "sofascore_column": "own_goals",
        "main_column": "player_own_goals",
        "sorare_action": "Own goal",
        "category": "Decisive",
        "scoring_type": "decisive_negative",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Own goal lowers Sorare Decisive Score level.",
    },
    "error_lead_to_a_goal": {
        "sofascore_column": "error_lead_to_a_goal",
        "main_column": "player_error_lead_to_a_goal",
        "sorare_action": "Error leading to goal",
        "category": "Decisive",
        "scoring_type": "decisive_negative",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Error leading to a goal lowers Sorare Decisive Score level.",
    },
    "penalty_conceded": {
        "sofascore_column": "penalty_conceded",
        "main_column": "player_penalty_conceded",
        "sorare_action": "Penalty conceded",
        "category": "Decisive",
        "scoring_type": "decisive_negative",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Penalty conceded lowers Sorare Decisive Score level.",
    },
    "penalty_miss": {
        "sofascore_column": "penalty_miss",
        "main_column": "player_penalty_miss",
        "sorare_action": "Penalty missed",
        "category": "Decisive",
        "scoring_type": "decisive_negative",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Treated as a negative decisive action in this analytical mapping.",
    },
    "red_card": {
        "sofascore_column": "red_card",
        "main_column": "v3_TMRedCards",
        "sorare_action": "Red card",
        "category": "Decisive",
        "scoring_type": "decisive_negative",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Red card lowers Sorare Decisive Score level.",
    },
    "yellow_card": {
        "sofascore_column": "yellow_card",
        "main_column": "v3_TMYellowCards",
        "sorare_action": "Yellow card",
        "category": "Discipline",
        "scoring_type": "all_around_negative",
        "points": {"GK": -3, "DEF": -3, "MID": -3, "FWD": -3},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Matrix row YELLOW_CARD.",
    },
    "error_lead_to_a_shot": {
        "sofascore_column": "error_lead_to_a_shot",
        "main_column": "player_error_lead_to_a_shot",
        "sorare_action": "Error leading to shot",
        "category": "Discipline",
        "scoring_type": "all_around_negative",
        "points": {"GK": -5, "DEF": -5, "MID": -3, "FWD": -3},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Matrix row ERROR_LEAD_TO_SHOT.",
    },
    "clean_sheet_60": {
        "sofascore_column": "clean_sheet_60",
        "main_column": "player_clean_sheet_60",
        "sorare_action": "Clean sheet, 60+ minutes",
        "category": "Defending",
        "scoring_type": "all_around",
        "points": {"GK": 0, "DEF": 10, "MID": 0, "FWD": 0},
        "applies_to_positions": ["DEF"],
        "notes": "Derived stat from minutes and team goals against. Matrix row CLEAN_SHEET_60 for defenders; goalkeeper clean sheet is handled separately as a Decisive action.",
    },
    "goals_conceded": {
        "sofascore_column": "goals_conceded",
        "main_column": "player_goals_conceded",
        "sorare_action": "Goals conceded",
        "category": "Defending",
        "scoring_type": "all_around_negative",
        "points": {"GK": -3, "DEF": -4, "MID": -2, "FWD": 0},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Derived from team goals against. Matrix row GOALS_CONCEDED.",
    },
    "won_tackle": {
        "sofascore_column": "won_tackle",
        "main_column": "player_won_tackle",
        "sorare_action": "Tackle won",
        "category": "Defending",
        "scoring_type": "all_around",
        "points": {"GK": 0, "DEF": 3, "MID": 3, "FWD": 0},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row WON_TACKLE.",
    },
    "interception_won": {
        "sofascore_column": "interception_won",
        "main_column": "player_interception_won",
        "sorare_action": "Interception",
        "category": "Defending",
        "scoring_type": "all_around",
        "points": {"GK": 0, "DEF": 3, "MID": 3, "FWD": 3},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row INTERCEPTION_WON.",
    },
    "total_clearance": {
        "sofascore_column": "total_clearance",
        "main_column": "player_total_clearance",
        "sorare_action": "Clearance",
        "category": "Defending",
        "scoring_type": "all_around",
        "points": {"GK": 0, "DEF": 0.5, "MID": 0, "FWD": 0},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Uses total clearances as proxy for effective clearances.",
    },
    "outfielder_block": {
        "sofascore_column": "outfielder_block",
        "main_column": "player_outfielder_block",
        "sorare_action": "Blocked shot",
        "category": "Defending",
        "scoring_type": "all_around",
        "points": {"GK": 0, "DEF": 2, "MID": 1, "FWD": 0},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row OUTFIELDER_BLOCK.",
    },
    "duel_won": {
        "sofascore_column": "duel_won",
        "main_column": "player_duel_won",
        "sorare_action": "Duel won",
        "category": "Duels",
        "scoring_type": "all_around",
        "points": {"GK": 0, "DEF": 1.5, "MID": 0.8, "FWD": 1},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row DUEL_WON.",
    },
    "duel_lost": {
        "sofascore_column": "duel_lost",
        "main_column": "player_duel_lost",
        "sorare_action": "Duel lost",
        "category": "Duels",
        "scoring_type": "all_around_negative",
        "points": {"GK": 0, "DEF": -2, "MID": -0.8, "FWD": -1},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row DUEL_LOST.",
    },
    "aerial_won": {
        "sofascore_column": "aerial_won",
        "main_column": "player_aerial_won",
        "sorare_action": "Aerial duel won",
        "category": "Duels",
        "scoring_type": "not_mapped",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "No separate official matrix row found; included as unmapped SofaScore stat.",
    },
    "aerial_lost": {
        "sofascore_column": "aerial_lost",
        "main_column": "player_aerial_lost",
        "sorare_action": "Aerial duel lost",
        "category": "Duels",
        "scoring_type": "not_mapped",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "No separate official matrix row found; included as unmapped SofaScore stat.",
    },
    "accurate_pass": {
        "sofascore_column": "accurate_pass",
        "main_column": "player_accurate_pass",
        "sorare_action": "Accurate pass",
        "category": "Passing",
        "scoring_type": "all_around",
        "points": {"GK": 0.1, "DEF": 0.08, "MID": 0.1, "FWD": 0.1},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row ACCURATE_PASS.",
    },
    "accurate_long_balls": {
        "sofascore_column": "accurate_long_balls",
        "main_column": "player_accurate_long_balls",
        "sorare_action": "Accurate long ball",
        "category": "Passing",
        "scoring_type": "all_around",
        "points": {"GK": 0.2, "DEF": 0.5, "MID": 0.5, "FWD": 0},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row ACCURATE_LONG_BALLS.",
    },
    "missed_pass": {
        "sofascore_column": "missed_pass",
        "main_column": "player_missed_pass",
        "sorare_action": "Missed pass",
        "category": "Passing",
        "scoring_type": "all_around_negative",
        "points": {"GK": -0.2, "DEF": -0.2, "MID": -0.3, "FWD": 0},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Derived as total_pass - accurate_pass. Matrix row MISSED_PASS.",
    },
    "key_pass": {
        "sofascore_column": "key_pass",
        "main_column": "player_key_pass",
        "sorare_action": "Attempted assist",
        "category": "Passing",
        "scoring_type": "all_around",
        "points": {"GK": 2, "DEF": 3, "MID": 2, "FWD": 2},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Uses key passes as proxy for adjusted attempted assists.",
    },
    "big_chance_created": {
        "sofascore_column": "big_chance_created",
        "main_column": "player_big_chance_created",
        "sorare_action": "Big chance created",
        "category": "Passing",
        "scoring_type": "all_around",
        "points": {"GK": 3, "DEF": 3, "MID": 3, "FWD": 3},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row BIG_CHANCE_CREATED.",
    },
    "on_target_scoring_attempt": {
        "sofascore_column": "on_target_scoring_attempt",
        "main_column": "player_on_target_scoring_attempt",
        "sorare_action": "Shot on target",
        "category": "Attacking",
        "scoring_type": "all_around",
        "points": {"GK": 3, "DEF": 3, "MID": 3, "FWD": 3},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row ONTARGET_SCORING_ATT.",
    },
    "won_contest": {
        "sofascore_column": "won_contest",
        "main_column": "player_won_contest",
        "sorare_action": "Successful dribble",
        "category": "Attacking",
        "scoring_type": "all_around",
        "points": {"GK": 0, "DEF": 0.5, "MID": 0.5, "FWD": 0.5},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row WON_CONTEST.",
    },
    "big_chance_missed": {
        "sofascore_column": "big_chance_missed",
        "main_column": "player_big_chance_missed",
        "sorare_action": "Big chance missed",
        "category": "Attacking",
        "scoring_type": "all_around_negative",
        "points": {"GK": -5, "DEF": -5, "MID": -5, "FWD": -5},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row BIG_CHANCE_MISSED.",
    },
    "possession_lost_ctrl": {
        "sofascore_column": "possession_lost_ctrl",
        "main_column": "player_possession_lost_ctrl",
        "sorare_action": "Possession lost",
        "category": "Possession",
        "scoring_type": "all_around_negative",
        "points": {"GK": -0.3, "DEF": -0.6, "MID": -0.5, "FWD": -0.1},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row POSS_LOST_CTRL.",
    },
    "ball_recovery": {
        "sofascore_column": "ball_recovery",
        "main_column": "player_ball_recovery",
        "sorare_action": "Possession won",
        "category": "Possession",
        "scoring_type": "all_around",
        "points": {"GK": 0, "DEF": 0.5, "MID": 0.5, "FWD": 0},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Uses ball recoveries as proxy for possession won.",
    },
    "was_fouled": {
        "sofascore_column": "was_fouled",
        "main_column": "player_was_fouled",
        "sorare_action": "Fouls won",
        "category": "Discipline",
        "scoring_type": "all_around",
        "points": {"GK": 0, "DEF": 0, "MID": 1, "FWD": 1},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row WAS_FOULED.",
    },
    "fouls": {
        "sofascore_column": "fouls",
        "main_column": "player_fouls",
        "sorare_action": "Fouls committed",
        "category": "Discipline",
        "scoring_type": "all_around_negative",
        "points": {"GK": -1, "DEF": -2, "MID": -1, "FWD": -0.5},
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "Official matrix row FOULS.",
    },
    "saves": {
        "sofascore_column": "saves",
        "main_column": "player_saves",
        "sorare_action": "Save",
        "category": "Goalkeeping",
        "scoring_type": "all_around",
        "points": {"GK": 2, "DEF": None, "MID": None, "FWD": None},
        "applies_to_positions": ["GK"],
        "notes": "Official matrix row SAVES.",
    },
    "saved_shots_from_inside_the_box": {
        "sofascore_column": "saved_shots_from_inside_the_box",
        "main_column": "player_saved_shots_from_inside_the_box",
        "sorare_action": "Save from inside box",
        "category": "Goalkeeping",
        "scoring_type": "all_around",
        "points": {"GK": 2, "DEF": None, "MID": None, "FWD": None},
        "applies_to_positions": ["GK"],
        "notes": "Official matrix row SAVED_IBOX.",
    },
    "accurate_keeper_sweeper": {
        "sofascore_column": "accurate_keeper_sweeper",
        "main_column": "player_accurate_keeper_sweeper",
        "sorare_action": "Accurate keeper sweeper",
        "category": "Goalkeeping",
        "scoring_type": "all_around",
        "points": {"GK": 3, "DEF": None, "MID": None, "FWD": None},
        "applies_to_positions": ["GK"],
        "notes": "Official matrix row ACCURATE_KEEPER_SWEEPER.",
    },
    "good_high_claim": {
        "sofascore_column": "good_high_claim",
        "main_column": "player_good_high_claim",
        "sorare_action": "Good high claim",
        "category": "Goalkeeping",
        "scoring_type": "all_around",
        "points": {"GK": 1.5, "DEF": None, "MID": None, "FWD": None},
        "applies_to_positions": ["GK"],
        "notes": "Official matrix row GOOD_HIGH_CLAIM.",
    },
    "punches": {
        "sofascore_column": "punches",
        "main_column": "player_punches",
        "sorare_action": "Punch",
        "category": "Goalkeeping",
        "scoring_type": "all_around",
        "points": {"GK": 1.5, "DEF": None, "MID": None, "FWD": None},
        "applies_to_positions": ["GK"],
        "notes": "Official matrix row PUNCHES.",
    },
    "cross_not_claimed": {
        "sofascore_column": "cross_not_claimed",
        "main_column": "player_cross_not_claimed",
        "sorare_action": "Cross not claimed",
        "category": "Goalkeeping",
        "scoring_type": "all_around_negative",
        "points": {"GK": -3, "DEF": None, "MID": None, "FWD": None},
        "applies_to_positions": ["GK"],
        "notes": "Official matrix row CROSS_NOT_CLAIMED.",
    },
    "goals_prevented": {
        "sofascore_column": "goals_prevented",
        "main_column": "player_goals_prevented",
        "sorare_action": "Goals prevented",
        "category": "Goalkeeping",
        "scoring_type": "not_mapped",
        "points": None,
        "applies_to_positions": ["GK"],
        "notes": "Useful goalkeeper impact stat, but no exact official Sorare matrix row was found.",
    },
    "total_offside": {
        "sofascore_column": "total_offside",
        "main_column": "player_total_offside",
        "sorare_action": "Offside",
        "category": "Attacking",
        "scoring_type": "not_mapped",
        "points": None,
        "applies_to_positions": ["GK", "DEF", "MID", "FWD"],
        "notes": "No official matrix row found in this project.",
    },
}


SOFASCORE_RAW_STAT_COLUMNS = [
    "total_shots",
    "on_target_scoring_attempt",
    "shot_off_target",
    "blocked_scoring_attempt",
    "expected_goals",
    "expected_goals_on_target",
    "big_chance_missed",
    "goals",
    "goal_assist",
    "touches",
    "total_pass",
    "accurate_pass",
    "missed_pass",
    "key_pass",
    "expected_assists",
    "total_long_balls",
    "accurate_long_balls",
    "total_cross",
    "accurate_cross",
    "total_contest",
    "won_contest",
    "duel_won",
    "duel_lost",
    "aerial_won",
    "aerial_lost",
    "total_tackle",
    "won_tackle",
    "interception_won",
    "total_clearance",
    "outfielder_block",
    "ball_recovery",
    "fouls",
    "was_fouled",
    "possession_lost_ctrl",
    "dispossessed",
    "unsuccessful_touch",
    "saves",
    "saved_shots_from_inside_the_box",
    "goals_prevented",
    "accurate_keeper_sweeper",
    "total_keeper_sweeper",
    "good_high_claim",
    "punches",
    "cross_not_claimed",
    "clearance_off_line",
    "clean_sheet_60",
    "goals_conceded",
    "last_man_tackle",
    "total_offside",
    "big_chance_created",
    "penalty_won",
    "penalty_conceded",
    "penalty_miss",
    "penalty_save",
    "own_goals",
    "red_card",
    "yellow_card",
    "error_lead_to_a_goal",
    "error_lead_to_a_shot",
]
